spring :
  h2:
    console: true
    path: /h2-console    #localhost:8080/h2-console 입력하면 된다.
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa :
    hibernate :
      ddl-auto: create
    properties:
      hibernate:
        show_sql : true
        format_sql : true
        default_batch_fetch_size : 100
    open-in-view: false

  devtools:   # 정적자원 캐시사용안함=> 새로고침시 바로바로,   but 실제서버운영시 캐시 사용해야된다
    livereload :
      enabled : true
    freemarker:
      cache: false
    restart:
      enabled: false
    thymeleaf:
      cache: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace





